CONNECT TO VSISP USER VSISP18;

CREATE TABLE CONTRACT(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  CONTRACT_NO INT,
  START_DATE DATE,
  PLACE VARCHAR(25)
);

CREATE TABLE PERSON(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  FIRST_NAME VARCHAR(25),
  NAME VARCHAR(25),
  ADDRESS VARCHAR(25)
);

CREATE TABLE ESTATE_AGENT(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  NAME varchar(255),
  ADDRESS varchar(255),
  LOGIN varchar(40) UNIQUE NOT NULL,
  PASSWORD varchar(40)
);

CREATE TABLE ESTATE(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  CITY VARCHAR(25),
  POSTAL_CODE INT,
  STREET VARCHAR(25),
  STREET_NUMBER INT,
  SQUARE_AREA INT,
  ESTATE_AGENT_LOGIN VARCHAR(25),
  CONSTRAINT FK_E_A_L FOREIGN KEY (ESTATE_AGENT_LOGIN) REFERENCES ESTATE_AGENT(LOGIN)
);

CREATE TABLE APARTMENT(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  FLOOR_NUMBER INT,
  RENT INT,
  ROOMS INT,
  BALCONY INT ,
  BUILT_IN_KITCHEN INT,
  CONSTRAINT FK_E_ID FOREIGN KEY (ID) REFERENCES ESTATE(ID)
);

CREATE TABLE HOUSE(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  FLOORS INT,
  PRICE INT,
  GARDEN INT,
  CONSTRAINT FK_E_ID FOREIGN KEY (ID) REFERENCES ESTATE(ID)
);

CREATE TABLE TENANCY_CONTRACT(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  START_DATE DATE,
  DURATION_IN_MONTH INT,
  ADDITIONAL_COSTS INT,
  APARTMENT_ID INT UNIQUE NOT NULL,
  CONSTRAINT FK_A_ID FOREIGN KEY (APARTMENT_ID) REFERENCES APARTMENT(ID),
  PERSON_ID INT NOT NULL,
  CONSTRAINT FK_P_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
  CONSTRAINT FK_C_ID FOREIGN KEY (ID) REFERENCES CONTRACT(ID)
);

CREATE TABLE PURCHASE_CONTRACT(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE) PRIMARY KEY,
  NO_OF_INSTALLMENTS INT,
  INTREST_RATE FLOAT,
  HOUSE_ID INT NOT NULL,
  CONSTRAINT FK_A_ID FOREIGN KEY (HOUSE_ID) REFERENCES HOUSE(ID),
  PERSON_ID INT NOT NULL,
  CONSTRAINT FK_P_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
  CONSTRAINT FK_C_ID FOREIGN KEY (ID) REFERENCES CONTRACT(ID)
);

COMMIT WORK;

CONNECT RESET;
